@startuml
package Client {
    abstract class Shape {
        +{abstract} draw()
        +{abstract} accept(ShapeVisitor* v)
        +{abstract} toString() : String
        +{abstract} save()
        +{abstract} translation()
        +{abstract} homothétie()
        +{abstract} rotation()
        +{abstract} getArea()
    }

    abstract class ComposedShape {
        +draw()
        +accept(ShapeVisitor* v)
        +toString() : String
        +save()
        +translation()
        +homothétie()
        +rotation()
        +getArea()
    }

    class Cercle {
        +draw()
        +accept(ShapeVisitor* v)
        +toString() : String
        +save()
        +translation()
        +homothétie()
        +rotation()
        +getArea()
    }
    class Segment {
        +draw()
        +accept(ShapeVisitor* v)
        +toString() : String
        +save()
        +translation()
        +homothétie()
        +rotation()
        +getArea()
    }
    class Triangle {
        +draw()
        +accept(ShapeVisitor* v)
        +toString() : String
        +save()
        +translation()
        +homothétie()
        +rotation()
        +getArea()
    }
    class Polygone {
        +draw()
        +accept(ShapeVisitor* v)
        +toString() : String
        +save()
        +translation()
        +homothétie()
        +rotation()
        +getArea()
    }
    class Socket << Singleton >> {
        -instance: Socket
        -Socket()
        +getInstance() : Socket
        +connectToServer()
    }

    abstract class ShapeVisitor {
        +{abstract} draw(Cercle *s)
        +{abstract} draw(Segment *s)
        +{abstract} draw(Triangle *s)
        +{abstract} draw(Polygone *s)
    }
}

package Serveur {
    class Thread
    class DrawingServer {
        +main()
    }
    class DrawingThread {
        +run()
    }

    class ShapeDrawer {
        +{abstract}draw(String request)
    }

    note "Peut être pas utile" as N1

    ShapeDrawer..N1

    class ShapeDrawerLink {
        +ShapeDrawerLink(ShapeDrawerLink next)
        +{abstract} drawShape(String request)
        +draw(String request)
    }

    class SegmentDrawer {
        +SegmentDrawer(ShapeDrawerLink next)
        +drawShape(String request)
    }

    class TriangleDrawer {
        +TriangleDrawer(ShapeDrawerLink next)
        +drawShape(String request)
    }

    class CircleDrawer {
        +CircleDrawer(ShapeDrawerLink next)
        +drawShape(String request)
    }

    class PolygoneDrawer {
        +PolygoneDrawer(ShapeDrawerLink next)
        +drawShape(String request)
    }

}
Shape <|-- Cercle
Shape <|-- Segment
Shape <|-- Triangle
Shape <|-- Polygone
DrawingServer *-- "0,N" DrawingThread
Thread <|-- DrawingThread
ShapeDrawer <|-- ShapeDrawerLink
ShapeDrawerLink o-- "0, 1" ShapeDrawerLink
ShapeDrawerLink <|-- SegmentDrawer
ShapeDrawerLink <|-- TriangleDrawer
ShapeDrawerLink <|-- CircleDrawer
ShapeDrawerLink <|-- PolygoneDrawer
DrawingThread *-- "1" ShapeDrawer
ComposedShape o-- "1, N" Shape
Shape <|-- ComposedShape
@enduml
